### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by wasyady** [Totenfluch/tVip#1]
I using tVIP (1.2) with tVip_testVipDuration "0".

L 03/11/2017 - 00:12:54: [SM] Exception reported: Array index is out of bounds
L 03/11/2017 - 00:12:54: [SM] Blaming: tVip.smx
L 03/11/2017 - 00:12:54: [SM] Call stack trace:
L 03/11/2017 - 00:12:54: [SM]   [1] Line 81, C:\Users\Christian\Dropbox\SourcePawnSP\tVIP\release\tVip.sp::OnConfigsExecuted
L 03/11/2017 - 00:13:10: [SM] Exception reported: Array index is out of bounds
L 03/11/2017 - 00:13:10: [SM] Blaming: tVip.smx
L 03/11/2017 - 00:13:10: [SM] Call stack trace:
L 03/11/2017 - 00:13:10: [SM]   [1] Line 382, C:\Users\Christian\Dropbox\SourcePawnSP\tVIP\release\tVip.sp::setFlags
L 03/11/2017 - 00:13:10: [SM]   [2] Line 375, C:\Users\Christian\Dropbox\SourcePawnSP\tVIP\release\tVip.sp::SQLCheckVIPQuery
L 03/11/2017 - 00:27:46: Error log file session closed.

**Comment by Totenfluch** [comment]
post your config file please

**Comment by wasyady** [comment]
`Listing 7 plugins:
           [01] SourceMod (1.8.0.5967) by AlliedModders LLC
           [02] CS Tools (1.8.0.5967) by AlliedModders LLC
           [03] SDK Tools (1.8.0.5967) by AlliedModders LLC
           [04] DHooks (2.1.0) by Dr!fter
           [05] SDK Hooks (1.8.0.5967) by AlliedModders LLC
           [06] SteamWorks Extension (1.2.1) by Kyle Sanderson`


`[SM] Listing 83 plugins:
           01 "[CS:GO/CSS] AbNeR Round End Sounds Simple" (3.4) by AbNeR_CSS
           02 "AC Gloves" (1.5.1) by Aircraft(diller110)
           03 "Admin all spec" (1.0.2) by Dr!fter
           04 "Admin File Reader" (1.8.0.5967) by AlliedModders LLC
           05 "Admin Help" (1.8.0.5967) by AlliedModders LLC
           06 "Admin Menu" (1.8.0.5967) by AlliedModders LLC
           07 "Admin & PlayerTags" (5.0) by shanapu
           08 "C4Timer CSGO" (1.5.0) by dalto, Panda
           09 "Advertisements" (2.0.2) by Tsunami
           10 "AFK Manager" (2.8) by Liam
           11 "Anti-Flood" (1.8.0.5967) by AlliedModders LLC
           12 "Basic Chat" (1.8.0.5967) by AlliedModders LLC
           13 "Basic Comm Control" (1.8.0.5967) by AlliedModders LLC
           14 "Basic Commands" (1.8.0.5967) by AlliedModders LLC
           15 "Basic Info Triggers" (1.8.0.5967) by AlliedModders LLC
           16 "Basic Votes" (1.8.0.5967) by AlliedModders LLC
           17 "Plant limiter" (1.2.3) by Tomasz 'anacron' Motylinski
           18 "CallAdmin" (0.1.5) by Impact, Popoklopsi
           19 "CallAdmin: Steam module" (0.1.5) by Impact, Popoklopsi
           20 "Client Preferences" (1.8.0.5967) by AlliedModders LLC
           21 "CS:GO Admin ESP" (2.1) by Root
           22 "SM CS:GO New Items" (1.1) by Franc1sco franug
           23 "CSS Bank" (1.6.6) by Miraculix
           24 "cURL self test" (1.1.0.0) by Raydan
           25 "[Source 2013] Custom Chat Colors" (3.1.1-CSGO) by Dr. McKay | Mitchell | Franc1sco
           26 "Dissolve" (1.0.0.2) by L. Duke
           27 "[CS:GO] Fake Competitive Rank and coins" (1.1b-wm) by Laam4
           28 "SM Franug CSGO Sprays" (1.4.2) by Franc1sco Steam: franug, EMINEM
           29 "CS:GO GiveNamedItem Hook Franug Edition" (4.0 private version) by Franc1sco franug and Neuro Toxin
           30 "SM CS:GO Weapon Paints" (6.3 private version) by Franc1sco franug
           31 "Fun Commands" (1.8.0.5967) by AlliedModders LLC
           32 "Fun Votes" (1.8.0.5967) by AlliedModders LLC
           33 "GameVoting" (1.8.2dev) by Neatek
           34 "[ANY] Ban Disconnected Player" (2.0) by Headline, Original Plugin : mad_hamster
           35 "High Ping Kicker - Lite Edition" (1.0.0.1) by Liam
           36 "IP Chat Block" (1.4) by SuperRaWR
           37 "RankMe" (3.0.3.Kento.22) by lok1, Scooby, pracc, Kento
           38 "MapChooser" (1.8.0.5964) by AlliedModders LLC
           39 "SM Most Active" (2.2) by Franc1sco Steam: franug
           40 "Nextmap" (1.8.0.5967) by AlliedModders LLC
           41 "Nikooo777" (1.0) by Nikooo777
           42 "Map Nominations" (1.8.0.5964) by AlliedModders LLC
           43 "Player Commands" (1.8.0.5967) by AlliedModders LLC
           44 "Player models by flags" (1.2) by boomix
           45 "[CSGO] QuakeSounds Overlays edition" (1.0) by TonyBaretta
           46 "RandomCycle" (1.8.0.5964) by AlliedModders LLC
           47 "refressher.smx"
           48 "Reserved Slots" (1.8.0.5967) by AlliedModders LLC
           49 "Rock The Vote" (1.8.0.5964) by AlliedModders LLC
           50 "SourceBans Checker" ((SB++) 1.5.4.6) by psychonic, Ca$h Munny, Sarabveer(VEER™)
           51 "SourceBans: Admin Config Loader" ((SB++) 1.5.4.6) by AlliedModders LLC, Sarabveer(VEER™)
           52 "Simple Chat Processor (Redux)" (2.1.0) by Simple Plugins, Mini
           53 "SourceMod Anti-Cheat" (0.8.6.0) by SMAC Development Team
           54 "SMAC Aimbot Detector" (0.8.6.0) by SMAC Development Team
           55 "SMAC AutoTrigger Detector" (0.8.6.0) by SMAC Development Team
           56 "SMAC Client Protection" (0.8.6.0) by SMAC Development Team
           57 "SMAC Command Monitor" (0.8.6.0) by SMAC Development Team
           58 "SMAC ConVar Checker" (0.8.6.0) by SMAC Development Team
           59 "SMAC EAC Global Banlist" (0.8.6.0) by SMAC Development Team
           60 "SMAC ESEA Global Banlist" (0.8.6.0) by SMAC Development Team
           61 "SMAC Eye Angle Test" (0.8.6.0) by SMAC Development Team
           62 "SMAC Rcon Locker" (0.8.6.0) by SMAC Development Team
           63 "SMAC Anti-Speedhack" (0.8.6.0) by SMAC Development Team
           64 "SMAC Spinhack Detector" (0.8.6.0) by SMAC Development Team
           65 "[CSGO] Advanced Admin" (1.5.8) by PeEzZ
           66 "Client Execute" (1.0.0.3) by dubbeh
           67 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
           68 "SM CS:GO Franug Knives" (3.0.5 private version) by Franc1sco franug
           69 "sm_plugins_block.smx"
           70 "Sound Commands" (1.8.0.5967) by AlliedModders LLC
           71 "SourceBans++" (1.5.4.6) by SourceBans Development Team, Sarabveer(VEER™)
           72 "SourceComms" ((SB++) 1.5.4.6) by Alex, Sarabveer(VEER™)
           73 "SourceSleuth" ((SB++) 1.5.4.6) by ecca, Sarabveer(VEER™)
           74 "Simple Stealth" (1.0) by Potatoz
           75 "Rotate server graphic banners" (0.3) by HiTmAnY
           76 "Thirdperson" (1.6 CS:GO edition) by shavit and Franc1sco franug
           77 "tVIP" (1.2) by Totenfluch
           78 "[VIP] Core" (2.1.1 R) by R1KO (skype: vova.andrienko1)
           79 "Weapon Restrict" (3.1.6) by Dr!fter
           80 "Web Shortcuts CS:GO version" (2.4) by Franc1sco franug and James "sslice" Gray
           81 "Zeus Round" (0.0.2.4) by TnTSCS aka ClarkKent`

**Comment by Totenfluch** [comment]
tVip.cfg

**Comment by wasyady** [comment]
// Default: "0"
tVip_flag "0"

// Test Vip duration in minutes
// -
// Default: "0"
tVip_testVipDuration "0"

**Comment by Totenfluch** [comment]
update to 1.3

kind regards

**Comment by wasyady** [comment]
Thanks for help!

I try it!
