### ISSUE TITLE
Still Doesn't Work

### ISSUE THREAD

**Issue by RikiGomes** [Totenfluch/tVip#10]
```
L 03/25/2019 - 20:25:23: [SM] Exception reported: Invalid query Handle 0 (error: 4)
L 03/25/2019 - 20:25:23: [SM] Blaming: tVip.smx
L 03/25/2019 - 20:25:23: [SM] Call stack trace:
L 03/25/2019 - 20:25:23: [SM]   [0] SQL_FetchRow
L 03/25/2019 - 20:25:23: [SM]   [1] Line 483, D:\SourcepawnScripts\tVip.sp::SQLCheckVIPQuery
L 03/25/2019 - 20:25:30: Error log file session closed.```

Still Occurs did the SET SQL_MODE='ALLOW_INVALID_DATES';

and my databases.cfg is configured like this

```
"tVip"
    {
		"driver"			"mysql"
		"host"				"ip"
		"database"			"mostwanted"
		"user"				"user"
		"pass"				"password"
		//"timeout"			"0"
		"port"			    "3306"
	}```

**Comment by RikiGomes** [comment]
Please don't close without me having the chance to answer.....

**Comment by Totenfluch** [comment]
I have seen this countless times as you can probably see in the plugin thread.
Howevery I'll give you the benefit of the doubt here.

RUN the commands in order and post me the full debug log

> sm_rcon sm plugins unload tVip
> 
> sm_rcon sm plugins load tVip
> 
> sm_rcon sm plugins load tVip
> 
> sm_rcon sm plugins reload tVip
> 
> sm_rcon sm plugins unload tVip
> 
> sm_rcon sm plugins reload tVip


After that go into your database and run

> CREATE TABLE IF NOT EXISTS `tVip` ( 
>  		`Id` bigint(20) NOT NULL AUTO_INCREMENT, 
>   		`timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, 
>   		`playername` varchar(36) COLLATE utf8_bin NOT NULL, 
>   		`playerid` varchar(20) COLLATE utf8_bin NOT NULL, 
>   		`enddate` timestamp NOT NULL DEFAULT '1970-01-01 00:00:00', 
>   		`admin_playername` varchar(36) COLLATE utf8_bin NOT NULL, 
>   		`admin_playerid` varchar(20) COLLATE utf8_bin NOT NULL, 
>  		 PRIMARY KEY (`Id`), 
>   		 UNIQUE KEY `playerid` (`playerid`)  
>   		 ) ENGINE = InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

you might need to remove linebreaks and \ depending on your mysql version (You can find the correct version in the .sp)

Then execute 
`SELECT * FROM tVip WHERE playerid = '%s' AND enddate > NOW();`

send me the FULL Debug log of both SQL commands

lastly
Add the full server version (operating system)
and MySQL version to your reply


kind regards

**Comment by RikiGomes** [comment]
Ok, so by creating the table manually like you suggested didn't work because it still had an invalid enddate, I changed it to 2000 and everything works fine, maybe test it in a test SQL server to be shure it doesn't hapen only to me. Thanks a lot and sorry to be so persistent but the plugin has so much potential I didn't want to give up on it!

**Comment by Totenfluch** [comment]
> Ok, so by creating the table manually like you suggested didn't work because it still had an invalid enddate, I changed it to 2000 and everything works fine, maybe test it in a test SQL server to be shure it doesn't hapen only to me. Thanks a lot and sorry to be so persistent but the plugin has so much potential I didn't want to give up on it!

SQL_MODE='ALLOW_INVALID_DATES'

fixes exactly the "invalid enddate" problem.

it is because you are running mysql 5.x which creates edge-cases.
