### ISSUE TITLE
SQLCheckVIPQuery Error

### ISSUE THREAD

**Issue by lazhoroni** [Totenfluch/tVip#12]
L 04/20/2019 - 20:15:05: [tVip.smx] Invalid default value for 'enddate'
L 04/20/2019 - 20:15:05: [tVip.smx] Table 'vipnot2easy.tVip' doesn't exist
L 04/20/2019 - 20:15:05: [SM] Exception reported: Invalid query Handle 0 (error: 4)
L 04/20/2019 - 20:15:05: [SM] Blaming: tVip.smx
L 04/20/2019 - 20:15:05: [SM] Call stack trace:
L 04/20/2019 - 20:15:05: [SM]   [0] SQL_FetchRow
L 04/20/2019 - 20:15:05: [SM]   [1] Line 483, tVip.sp::SQLCheckVIPQuery

**Comment by Totenfluch** [comment]
https://github.com/Totenfluch/tVip/commit/32712ff9a3a9057dc8a4ebb808ab06f705f4542c

worked with the latest .sp

the binary is also up to date now

**Comment by lazhoroni** [comment]
I'm having to repeat with the same errors. I can access the database seamlessly.
L 04/20/2019 - 20:15:05: [tVip.smx] Invalid default value for 'enddate'
L 04/20/2019 - 20:15:05: [tVip.smx] Table 'vipnot2easy.tVip' doesn't exist
L 04/20/2019 - 20:15:05: [SM] Exception reported: Invalid query Handle 0 (error: 4)
L 04/20/2019 - 20:15:05: [SM] Blaming: tVip.smx
L 04/20/2019 - 20:15:05: [SM] Call stack trace:
L 04/20/2019 - 20:15:05: [SM] [0] SQL_FetchRow
L 04/20/2019 - 20:15:05: [SM] [1] Line 483, tVip.sp::SQLCheckVIPQuery

**Comment by Totenfluch** [comment]
run

SET SQL_MODE='ALLOW_INVALID_DATES';

as described in https://forums.alliedmods.net/showthread.php?t=292183

you are running a very outdated version of mysql
