### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kaptenn** [Totenfluch/tVip#14]
L 06/17/2019 - 18:28:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 06/17/2019 - 18:28:33: [SM] Blaming: tVip.smx
L 06/17/2019 - 18:28:33: [SM] Call stack trace:
L 06/17/2019 - 18:28:33: [SM]   [0] SQL_SetCharset
L 06/17/2019 - 18:28:33: [SM]   [1] Line 56, E:\csgoserver\csgo_server\csgo\addons\sourcemod\scripting\tVip.sp::OnPluginStart
L 06/17/2019 - 18:28:33: [SM] Unable to load plugin "tVip.smx": Error detected in plugin startup (see error logs)

database.cfg:

	"tVip"
	{
		"driver" "mysql"
		"host" "localhost"
		"database" "vipsystem"
		"user" "root"
		"pass" ""
		//"timeout" "0"
		//"port" "3306"
	}

**Comment by Totenfluch** [comment]
looks like your credentials are invalid

**Comment by kaptenn** [comment]
Nope, i've doublechecked everything.. I really want this plugin to work :/

**Comment by Totenfluch** [comment]
add me on steam, send me the valid credentials to connect to your database and then I can have a look. Change the password before you give it to me and afterwards.

**Comment by kaptenn** [comment]
im hosting my server on my own pc (locally), is that a factor that should be considered?

also, i added you as a friend in steam, "kapten"

**Comment by Totenfluch** [comment]
Error in local config not the plugin

**Comment by Vaaalen123** [comment]
L 06/06/2021 - 00:12:21: [SM] Exception reported: Error connecting to database: "[2003]: Can't connect to MySQL server on 'localhost' (10061)"
L 06/06/2021 - 00:12:21: [SM] Blaming: tVip.smx
L 06/06/2021 - 00:12:21: [SM] Call stack trace:
L 06/06/2021 - 00:12:21: [SM]   [0] SetFailState
L 06/06/2021 - 00:12:21: [SM]   [1] Line 59, C:\Users\ziegl\Dropbox\SourcePawnSP\Products\tVIP\tVip\tVip.sp::OnPluginStart
L 06/06/2021 - 00:12:21: [SM] Unable to load plugin "tVip.smx": Error detected in plugin startup (see error logs)
L 06/06/2021 - 00:12:21: [SM] Fatal error encountered parsing translation file "tvip_reserved.phrases.txt"
L 06/06/2021 - 00:12:21: [SM] Error (line 0, column 0): Stream failed to open

**Comment by Vaaalen123** [comment]
Hello, the plugin does not work, there is an error

**Comment by Totenfluch** [comment]
You did not install the translations properly as directly seen in the error. Not a plugin issue.
