### ISSUE TITLE
Help! (Error)

### ISSUE THREAD

**Issue by chulicoxd** [Totenfluch/tVip#16]
Hi, how about I have a problem executing the plug-in? I have a hosted server, can little plugins help me?

![tvip](https://user-images.githubusercontent.com/60021173/75719831-39b12200-5cb4-11ea-8891-64717ef3cfba.png)

![logtvip](https://user-images.githubusercontent.com/60021173/75719996-8563cb80-5cb4-11ea-806e-189de619f25d.png)

**Comment by Totenfluch** [comment]
No.
This is a very simple installation error that could have been avoided if you would read the plugin thread: https://forums.alliedmods.net/showthread.php?t=292183

closed.

**Comment by chulicoxd** [comment]
I can't find that configuration since my server is hosted
![Sin título](https://user-images.githubusercontent.com/60021173/75721876-dde89800-5cb7-11ea-940f-b5923920968b.png)

I don't know where I find database.cfg.
