### ISSUE TITLE
Add Immunity to it?

### ISSUE THREAD

**Issue by 3GaNwO** [Totenfluch/tVip#6]
So I like how this setup works but I would like to be able to add Immunity to the flag I choose. Is that an option with this setup or something you may look into adding in the future?

**Comment by Totenfluch** [comment]
Adding it to the config like

```
"20:200 19:400"
Flag:Immunity
```

and parsing it wouldn't be a problem.

Adding it to the player would as it is designed as VIP System
which basically just gives the Flag and not "Admin".
For Immunity the Plugin would need to create an Admin Identity and add the Player to it.
That is kinda hard to accomplish but not impossibe. If more people request it I might implement it
as it is a good idea. But if it is only you the request is too time consuming I'm afraid.

I'd be happy to review a Pull request and make smaller fixes to it tho!

**Comment by 3GaNwO** [comment]
So are you saying that this could already work now doing that above ^ or that you would need to add more to the setup to get it to work like how you described above? (: 

If more work is needed to be done I would be willing to pay you to get something like this working but if we did this i would want this update to be private for me

**Comment by Totenfluch** [comment]
It needs an addition to make it work as described 
And no I'm not doing paid work that has to be kept private on a public plugin. Why would I have released it on the first place if I didn't want everything of it public...?

**Comment by 3GaNwO** [comment]
That does make sense to me. If I were to try and pay you for adding this how much would you charge for it? since the update to it will remain public i'm sure tons of other users will find the update valuable to them. I have a client that wants this done but he wants it done sooner than later and is why I ask how much you would charge if you would accept adding that into it. 

With that addition we would also like to see a couple more tables added to the database. Right now in the database I don't see a flags table. Could you add this one in and with the update an immunity table for the database to have? 

If you are strapped on time I completely understand. I just figured I could ask and find out

**Comment by Totenfluch** [comment]
Add me on steam and we can talk details. 
You will not catch me today anymore tho.

The immunity change cane be done pretty quickly if it's that important to you.

For the tables I'd need a detailed plan from you to see if your plan fits with the plugin or should be realised another way.

**Comment by 3GaNwO** [comment]
I have added you. I am OwNaG3. 

I look forward to talking more details about this. 
The immunity change is pretty important to the client and why I am asking (: 

the tables part is more for convenience and seeing it being databased properly. 
 
Anyways I really do like this plugin it works pretty well if I may say so myself

**Comment by Totenfluch** [comment]
as extensively discussed this does not work without breaking sourcebans compatibility

#closed
