### ISSUE TITLE
 authority and desire in everyone

### ISSUE THREAD

**Issue by lazhoroni** [Totenfluch/tVip#7]
1- Unauthorized players in my server began to appear as authorized.

2- Can you set the authority to be written according to the group?

**Comment by Totenfluch** [comment]
I don't understand either of those points. Plkease elaborate

**Comment by lazhoroni** [comment]
I do not authorize the players in the server, but it seems that there is authority in the players.
sorry for the bad language. I'm using translation.

**Comment by Totenfluch** [comment]
Are you running a non steam server?

**Comment by lazhoroni** [comment]
I'm using a steam server. Do you create a custom log file to see if there is an error when I activate the plugin?

**Comment by Totenfluch** [comment]
Nope. Just check the regular error logs
